export const countries = [
  { code: "af", text: "Afrikaans" },
  { code: "ar", text: "Arabic" },
  { code: "bn", text: "Bengali" },
  { code: "bg", text: "Bulgarian" },
  { code: "ca", text: "Catalan" },
  { code: "cs", text: "Czech" },
  { code: "da", text: "Danish" },
  { code: "de", text: "German" },
  { code: "el", text: "Greek" },
  { code: "en-US", text: "English (US)" },
  { code: "en-GB", text: "English (UK)" },
  { code: "es-ES", text: "Spanish (Spain)" },
  { code: "es-MX", text: "Spanish (Mexico)" },
  { code: "et", text: "Estonian" },
  { code: "fa", text: "Persian" },
  { code: "fi", text: "Finnish" },
  { code: "fr", text: "French" },
  { code: "gu", text: "Gujarati" },
  { code: "he", text: "Hebrew" },
  { code: "hi", text: "Hindi" },
  { code: "hr", text: "Croatian" },
  { code: "hu", text: "Hungarian" },
  { code: "id", text: "Indonesian" },
  { code: "it", text: "Italian" },
  { code: "ja", text: "Japanese" },
  { code: "jv", text: "Javanese" },
  { code: "ko", text: "Korean" },
  { code: "lt", text: "Lithuanian" },
  { code: "lv", text: "Latvian" },
  { code: "ml", text: "Malayalam" },
  { code: "mr", text: "Marathi" },
  { code: "ms", text: "Malay" },
  { code: "nl", text: "Dutch" },
  { code: "no", text: "Norwegian" },
  { code: "pa", text: "Punjabi" },
  { code: "pl", text: "Polish" },
  { code: "pt-BR", text: "Portuguese (Brazil)" },
  { code: "pt-PT", text: "Portuguese (Portugal)" },
  { code: "ro", text: "Romanian" },
  { code: "ru", text: "Russian" },
  { code: "si", text: "Sinhala" },
  { code: "sk", text: "Slovak" },
  { code: "sl", text: "Slovenian" },
  { code: "sv", text: "Swedish" },
  { code: "ta", text: "Tamil" },
  { code: "te", text: "Telugu" },
  { code: "th", text: "Thai" },
  { code: "tr", text: "Turkish" },
  { code: "uk", text: "Ukrainian" },
  { code: "vi", text: "Vietnamese" },
  { code: "zh-CN", text: "Chinese (Simplified)" },
  { code: "zh-TW", text: "Chinese (Traditional)" },
];
